# Generated by Django 5.2.7 on 2025-10-14 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0006_alter_county_options_alter_county_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Department Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mandate', models.TextField(blank=True, help_text='Core functions and responsibilities of this department.', null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('head_office_location', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('staff_count', models.PositiveIntegerField(default=0)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='locations.county')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='departments.departmentcategory')),
            ],
            options={
                'ordering': ['county__name', 'name'],
                'unique_together': {('county', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('WEBSITE', 'Website')], max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='departments.department')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Department Units',
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('is_head', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='departments.department')),
                ('subcounty', models.ForeignKey(blank=True, help_text='Area officer oversees within the county.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.subcounty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='departments.departmentunit')),
            ],
            options={
                'verbose_name_plural': 'Department Officers',
                'ordering': ['department__name', 'user__username'],
            },
        ),
    ]
