# Generated by Django 5.2.7 on 2025-10-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='country',
        ),
        migrations.RemoveField(
            model_name='locationlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='village',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='county',
            name='area_km2',
        ),
        migrations.RemoveField(
            model_name='county',
            name='email',
        ),
        migrations.RemoveField(
            model_name='county',
            name='governor',
        ),
        migrations.RemoveField(
            model_name='county',
            name='headquarters',
        ),
        migrations.RemoveField(
            model_name='county',
            name='map_coordinates',
        ),
        migrations.RemoveField(
            model_name='county',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='county',
            name='population',
        ),
        migrations.RemoveField(
            model_name='county',
            name='website',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='area_km2',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='headquarters',
        ),
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Official county code, e.g., 042 for Kisumu', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='locations.subcounty')),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'ordering': ['name'],
                'unique_together': {('sub_county', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ward',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='locations.constituency'),
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('constituency', 'name')},
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='LocationLog',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='area_km2',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='population',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='sub_county',
        ),
    ]
