# Generated by Django 5.2.7 on 2025-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_county_country_remove_locationlog_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['code'], 'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.PositiveSmallIntegerField(default=None, help_text='Official county code, e.g., 042 for Kisumu', unique=True),
        ),
    ]
