# Generated by Django 5.2.7 on 2025-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_county_options_alter_county_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.PositiveSmallIntegerField(default=0, help_text='Official county code, e.g., 042 for Kisumu', unique=True),
        ),
    ]
