# Generated by Django 5.2.7 on 2025-10-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_county_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.PositiveSmallIntegerField(help_text='Official county code, e.g., 042 for Kisumu', null=True, unique=True),
        ),
    ]
