# Generated by Django 5.2.7 on 2025-10-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_county_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name'], 'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Official county code, e.g., 042 for Kisumu', null=True, unique=True),
        ),
    ]
